# Generated by Django 3.2.5 on 2021-12-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_comment_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_date',)},
        ),
    ]
